# Generated by Django 5.2.5 on 2026-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('profile_updated', 'Profile Updated'), ('project_created', 'Project Created'), ('project_liked', 'Project Liked'), ('connection_made', 'Connection Made'), ('message_sent', 'Message Sent'), ('comment_added', 'Comment Added'), ('user_followed', 'User Followed'), ('task_completed', 'Task Completed'), ('milestone_completed', 'Milestone Completed')], max_length=30),
        ),
    ]
