# Generated by Django 5.2.5 on 2026-02-09 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_activity_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Apps'), ('ai', 'AI/ML'), ('data', 'Data Science'), ('blockchain', 'Blockchain'), ('iot', 'IoT'), ('game', 'Game Development'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='📁', max_length=50)),
                ('template_title', models.CharField(help_text='Template for project title', max_length=200)),
                ('template_description', models.TextField(help_text='Template for project description')),
                ('template_technologies', models.JSONField(default=list, help_text='Suggested technologies')),
                ('template_looking_for', models.JSONField(default=list, help_text='Suggested roles needed')),
                ('template_collaboration_needs', models.TextField(blank=True, null=True)),
                ('suggested_timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('suggested_team_size', models.CharField(blank=True, help_text="e.g., '2-3 people', 'solo', '5+ people'", max_length=100, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('example_projects', models.TextField(blank=True, help_text='Links to example projects', null=True)),
                ('learning_resources', models.TextField(blank=True, help_text='Links to tutorials/docs', null=True)),
                ('rating', models.FloatField(default=0, help_text='Average rating from 0-5')),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Number of ratings')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Times this template was used')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-rating', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='TemplateUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='accounts.projecttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review', models.TextField(blank=True, max_length=500, null=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='accounts.projecttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('template', 'user')},
            },
        ),
    ]
