services:
  - type: web
    name: unisync
    runtime: python
    runtimeVersion: 3.11.0
    buildCommand: cd backend && python manage.py collectstatic --noinput && bash build.sh
    startCommand: cd backend && gunicorn auth_project.wsgi:application --workers 3 --worker-class sync --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DEBUG
        value: "False"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
